# utils/reporting.py
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib import colors
from reportlab.lib.units import cm
import io
import os
from datetime import datetime

# Path to image that you uploaded earlier; adjust if needed.
HEADER_IMAGE_PATH = "/mnt/data/A_flowchart_and_data_flow_diagram_in_a_digital_ill.png"

def generate_session_report_pdf_bytes(session, answers, user):
    """
    session: InterviewSession SQLAlchemy object
    answers: list of InterviewAnswer objects (SQLAlchemy)
    user: User object
    returns: bytes of generated PDF
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    styleH = styles['Heading1']
    styleH.alignment = 1  # center
    styleN = styles['Normal']
    styleSmall = ParagraphStyle('small', parent=styles['Normal'], fontSize=9)

    elems = []

    # Header image (if file exists)
    if os.path.exists(HEADER_IMAGE_PATH):
        try:
            img = Image(HEADER_IMAGE_PATH, width=12*cm, height=4*cm)
            img.hAlign = 'CENTER'
            elems.append(img)
            elems.append(Spacer(1, 12))
        except Exception:
            # ignore image errors
            pass

    # Title
    title = f"VirtuHire — Interview Report"
    elems.append(Paragraph(title, styleH))
    elems.append(Spacer(1, 8))

    # Session summary
    meta = [
        ("Candidate", getattr(user, "full_name", user.email)),
        ("Email", user.email),
        ("Job Role", session.job_role or "-"),
        ("Company", session.company_name or "-"),
        ("Session ID", str(session.id)),
        ("Date", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"))
    ]
    # Make nice two-column table for metadata
    meta_table = Table(meta, colWidths=[4*cm, 10*cm])
    meta_table.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("TEXTCOLOR", (0,0), (-1,-1), colors.HexColor("#111827")),
        ("FONTSIZE", (0,0), (-1,-1), 10),
    ]))
    elems.append(meta_table)
    elems.append(Spacer(1, 12))

    # Session aggregated metrics (if present)
    metrics = [
        ["Metric", "Value"],
        ["Total Questions", str(session.total_questions or len(answers))],
        ["Final Pause-to-Speech Ratio", f"{getattr(session, 'final_pause_ratio', 'N/A')}"],
        ["Final Filler Rate", f"{getattr(session, 'final_filler_rate', 'N/A')}"],
        ["Final Stress Score", f"{getattr(session, 'final_stress_score', 'N/A')}"]
    ]
    mtable = Table(metrics, colWidths=[8*cm, 6*cm])
    mtable.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0ea5a4")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("GRID", (0,0), (-1,-1), 0.25, colors.gray),
    ]))
    elems.append(mtable)
    elems.append(Spacer(1, 14))

    # Per-question details (index, question, transcript, metrics)
    for i, ans in enumerate(sorted(answers, key=lambda a: a.question_index)):
        q_title = f"Q{i+1}. {ans.question_text or 'Question text unavailable'}"
        elems.append(Paragraph(q_title, styles['Heading3']))
        elems.append(Spacer(1, 6))

        # small metadata table per answer
        qmeta = [
            ["Duration (ms)", str(ans.total_duration_ms or 0)],
            ["Silence (ms)", str(ans.total_silence_ms or 0)],
            ["Speech (ms)", str(ans.total_speech_ms or 0)],
            ["Pause ratio", f"{ans.pause_to_speech_ratio or 0:.3f}"],
            ["Filler count", str(ans.filler_count or 0)],
            ["Stress level", str(ans.stress_level or "unknown")]
        ]
        qtable = Table(qmeta, colWidths=[6*cm, 6*cm])
        qtable.setStyle(TableStyle([
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
            ("GRID", (0,0), (-1,-1), 0.25, colors.lightgrey),
        ]))
        elems.append(qtable)
        elems.append(Spacer(1, 6))

        # Transcription text
        elems.append(Paragraph("<b>Transcription:</b>", styleSmall))
        trans_text = (ans.transcription or "").strip()
        if not trans_text:
            trans_text = "(No transcription available)"
        elems.append(Paragraph(trans_text.replace("\n", "<br/>"), styleSmall))
        elems.append(Spacer(1, 14))

    # Footer / generation note
    elems.append(Spacer(1, 10))
    elems.append(Paragraph("Generated by VirtuHire — AI Virtual Interviewer", styleSmall))
    elems.append(Spacer(1, 4))
    elems.append(Paragraph("Note: Metrics are algorithmic estimates. Use results for guidance.", styleSmall))

    # Build PDF
    doc.build(elems)

    buffer.seek(0)
    return buffer.getvalue()
